export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
    //NON-L0GGED-HOME-COMPONENT
    'We only charge': 'Sólo cobramos',
    'if you win': 'si tú ganas',
    "It will take you only a minute to claim your flight, it's that easy!": 'Te costará un minuto reclamar tu vuelo, ¡es muy fácil!',
    'Check compensation': 'Calcular compensación',
    'What can I claim?': '¿Qué puedo reclamar?',
    'Delay': 'Retraso',
    'You can get up to € 600 for any delay over 3 hours.': 'Puedes conseguir hasta 600€ por cualquier retraso superior a 3 horas.',
    'Cancellation': 'Cancelación',
    'If your flight has been cancelled or you have been assigned a different one, airlines owe you a compensation.': 'Si han cancelado tu vuelo o te han asignado uno distinto, te corresponde una compensación.',
    'Overbooking': 'Overbooking',
    'You are entitled to compensation in case of denied boarding.': 'Tienes derecho a una indemnización si te han denegado el embarque o entrada en el avión.',
    'How does Fly&Claim work?': '¿Cómo funciona Fly&Claim?',
    'Fill our form': 'Rellena nuestro formulario',
    'Enter your flight information and see if you are entitled to compensation, it will take you less than a minute!': 'Introduce los datos de tu vuelo y comprueba si tienes derecho a una compensación ¡Tardarás menos de un minuto!',
    'Our experts process your case': 'Nuestros expertos tramitan tu caso',
    'We have a team of professionals whose success rate is 99%. Forget about the paperwork, at Fly&Claim we take care of everything!':   'Contamos con un equipo de profesionales cuya tasa de éxito es del 99% ¡Olvídate del papeleo mientras en Fly&Claim nos ocupamos de todo!',
    "You get your money, it's that easy!": 'Recibes tu dinero ¡así de fácil!',
    'Once your claim is resolved, you will receive your money immediately. You can get from 250 to 600 euros per passenger.': 'Resuelta tu reclamación, recibirás tu dinero de inmediato. Puedes conseguir desde 250 hasta 600 euros por pasajero.',
    'We only charge if you win': 'Sólo cobramos si tu ganas',
    'Up to 600€ per person': 'Hasta 600€ por persona',
    'Forget about the paperwork': 'Olvídate del papeleo',
    'We inform you step by step of the process': 'Te informamos paso a paso del proceso',
    //APP-COMPONENT
    'Terms and Conditions': 'Términos y condiciones',
    'Privacy policy': 'Política de privacidad',
    'Cookies policy': 'Política de cookies',
    'Welcome to FlyAndClaim. By continuing browsing we consider that you accept our': 'Bienvenido a FlyAndClaim. Al continuar navegando consideramos que aceptas nuestra',
    'cookies policy.': 'política de cookies.',
    //SHARE-PROMO-COMPONENT
    'How does it work?': '¿Cómo funciona?',
    'Log in': 'Inicia sesión',
    'or sign up': 'o regístrate',
    'You will get a promotional code that you can share with anyone who has had an incident on your flight.': 'Obtendrás un código promocional que podrás compartir con cualquiera que haya tenido un incidente en su vuelo.',
    'Win 10€ each time': 'Gana 10€ cada vez',
    'they use your code': 'que utilizan tu código',
    'Share your promotional code. Friends, family, travel partners, anyone can be entitled to compensation and not know it.': 'Comparte tu código promocional. Amigos, familiares, compañeros de viaje, cualquiera puede tener derecho a una compensación y no saberlo.',
    'Everybody': 'Todos',
    'wins': 'ganamos',
    'If a passenger uses your code they will receive 10€ more in their compensation. Convince them and make them win more!': 'Si un pasajero utiliza tu código recibirá 10€ más en su compensación. ¡Convénceles y hazles ganar más!',
    'Control your': 'Controla tu',
    'activity': 'actividad',
    'You can see the status of your promotions in the section': 'Puedes ver el estado de tus promociones en el apartado',
    'Your promotional code': 'Tu código promocional',
    //NAV-HEADER-COMPONENT
    'End claim': 'Finalizar reclamación',
    'Contact': 'Contacto',
    'Share and earn money': 'Comparte y gana dinero',
    'Log out': 'Cerrar sesión',
    'My claims': 'Mis reclamaciones',
    'Your promotional code:': 'Tu código promocional:',
    'Home': 'Inicio',
    //LOGIN-COMPONENT
    'Login with Facebook': 'Iniciar sesión con Facebook',
    'Login with Google': 'Iniciar sesión con Google',
    'E-mail': 'Correo electrónico',
    'Required field': 'Campo requerido',
    'Invalid email format': 'Formato correo electrónico no válido',
    'Incorrect email address': 'Dirección de correo electrónico incorrecta',
    'Password': 'Contraseña',
    'Invalid password': 'Contraseña incorrecta',
    'Have you forgotten your password?': '¿Has olvidado tu contraseña?',
    'Don´t you have an account?': '¿No tienes una cuenta?',
    'Sign up': 'Regístrate',
    'or': 'o',
    //REGISTER-COMPONENT
    'Sign up with Facebook': 'Regístrate con Facebook',
    'Sign up with Google': 'Regístrate con Google',
    'Name': 'Nombre',
    'This email address already exists, try another': 'Esta dirección de correo electrónico ya existe, prueba con otra',
    'Already have an account in Fly&Claim?': '¿Ya tienes una cuenta en Fly&Claim?',
    //FORGOT-PASSWORD-COMPONENT
    'Restore password': 'Restablecer contraseña',
    'Enter the email address associated with your account and we will send you a link to reset your password.': 'Introduce la dirección de correo electrónico asociada a tu cuenta y te enviaremos un enlace para restablecer tu contraseña.',
    'Return to Login': 'Volver a Inicio de sesión',
    'Send link': 'Enviar enlace',
    //LOGGED-HOME-COMPONENT
    'Hello': 'Hola',
    'Thank you for finalizing your claim. Your promotional code is the': 'Gracias por finalizar tu reclamación. Tu código promocional es el',
    ', click': ', pincha',
    'here': 'aquí',
    'if you want to see your activity.': 'si quieres ver tu actividad.',
    'Your promotional code is the': 'Tu código promocional es el',
    'You have': 'Tienes',
    'pending claim to complete': 'reclamación pendiente de completar',
    'pending claims to complete': 'reclamaciones pendientes de completar',
    'from': 'de',
    ', to': ', a',
    ', claim created on': ', reclamación creada el',
    'Complete': 'Completar',
    'You have completed': 'Has completado',
    'claim': 'reclamación',
    'claims': 'reclamaciones',
    'Incidence': 'Incidencia',
    'Status': 'Estado',
    //MY-PROMO-COMPONENT
    'Your promotional': 'Tu código',
    'code': 'promocional',
    'If you want to know how you can earn money by sharing, click': 'Si quieres saber cómo puedes ganar dinero compartiendo, pincha',
    'Your activity': 'Tu actividad',
    'Code used': 'Código utilizado',
    'euros': 'euros',
    'aware of payment': 'pendientes de cobro',
    'earned': 'cobrados',
    'invalid': 'promociones',
    'promotions': 'no válidas',
    'time': 'vez',
    'times': 'veces',
    //CONTACT-COMPONENT
    'Contact us': 'Contacta',
    'with us': 'con nosotros',
    'We are happy to answer any questions you may have, just send us a message to our email or give us a call any day of the week from 9:30 a.m. to 9:30 p.m.': 'Nos complace responder a cualquier pregunta que puedas tener, sólo envíanos un mensaje a nuestro correo electrónico o llámanos cualquier día de la semana de 9:30 a 21:30.',
    'Telephone': 'Teléfono',
    //CLAIM-COMPONENT
    'Check your': 'Calcula tu',
    'compensation': 'compensación',
    'Airlines owe you': 'Te corresponden',
    'per passenger': 'por pasajero',
    'Log in or sign up': 'Inicia sesión o regístrate',
    'to earn your': 'para conseguir tus',
    "Congratulations, you've got": '¡Enhorabuena, has conseguido',
    'more thanks to the promotional code!': 'más gracias al código promocional!',
    'Finish your claim and our experts will process your compensation': 'Finaliza tu reclamación y nuestros expertos tramitarán tu indemnización',
    //SECOND-PART-CLAIM-COMPONENT
    'Airport where the incident occurred': 'Aeropuerto donde ocurrió el incidente',
    'Promotional code (opt)': 'Código promocional (opc)',
    'Flight year': 'Año del vuelo',
    'Required': 'Requerido',
    'Address': 'Domicilio',
    'ZIP': 'C.P.',
    'City': 'Ciudad',
    'Country': 'País',
    'Did you complain to the airline?': '¿Reclamaste a la compañía aérea?',
    'YES': 'SI',
    'NO': 'NO',
    'Do you have the flight reservation or ticket?': '¿Tienes la reserva o billete del vuelo?',
    'Do you have the boarding pass?': '¿Tienes la tarjeta de embarque?',
    'Tell us what happened (opt)': 'Cuéntanos lo sucedido (opc)',
    //RED-DIV-COMPONENT
    'Remember that if you do not have the flight reservation or ticket, or the boarding pass, we will not be able to process your claim.': 'Recuerda que si no tienes la reserva o billete del vuelo, ni la tarjeta de embarque, no podremos tramitar tu reclamación.',
    'You must attach at least one of these three documents:': 'Debes adjuntar al menos uno de estos tres documentos:',
    'Flight reservation.': 'Reserva del vuelo.',
    'Flight ticket.': 'Billete del vuelo.',
    'Boarding pass.': 'Tarjeta de embarque.',
    'You can find your flight reservation in the confirmation email that the airline sent you when you bought the tickets.': 'Puedes encontrar la reserva de tu vuelo en el correo electrónico de confirmación que te envío la aerolínea al comprar los billetes.',
    'Try searching the name of the airline in your email to find the reservation.': 'Prueba a buscar el nombre de la compañía aérea en tu correo eléctronico para encontrar la reserva.',
    'If you need help to find any of the above documents, send us an email to info@flyandclaim.com': 'Si necesitas ayuda para encontrar cualquiera de los documentos anteriores envíanos un correo electrónico a info@flyandclaim.com',
    //ID-FRONT-COMPONENT
    'Attach front image of ID / Passport': 'Adjuntar imagen delantera del DNI / Pasaporte',
    'Front image of ID / Passport': 'Imagen delantera del DNI / Pasaporte',
    //ID-BACK-COMPONENT
    'Attach back image of ID': 'Adjuntar imagen trasera del DNI',
    'Back image of ID': 'Imagen trasera del DNI',
    //FLIGHT-TICKET-OR-RESERVATION-COMPONENT
    'Attach reservation or flight ticket': 'Adjuntar reserva o billete del vuelo',
    //COMPANY-CLAIM-COMPONENT
    'Attach claim to the airline': 'Adjuntar reclamación a la compañía aérea',
    //BOARDING-PASS-COMPONENT
    'Attach boarding pass': 'Adjuntar tarjeta de embarque',
    //NO-C0MPENSATION-COMPONENT
    'We are sorry,': 'Lo sentimos,',
    'this flight does not give you the right': 'este vuelo no te da derecho',
    'to receive compensation': 'a recibir una compensación',
    'If you still believe that you are entitled to compensation or have doubts, contact us:': 'Si aún así crees que tienes derecho a una indemnización o tienes dudas, contáctanos:',
    //FIRST-PART-CLAIM-COMPONENT
    'From': 'Desde',
    'To': 'A',
    'Direct flight': 'Vuelo directo',
    'Flights with a stop': 'Vuelo con escala',
    'Airline': 'Aerolínea',
    'Delay less than 3 hours': 'Retraso inferior a 3 horas',
    'Delay greater than 3 hours': 'Retraso superior a 3 horas',
    'Add another stop': 'Añadir otra escala',
    'You must accept the General Conditions': 'Debes aceptar las condiciones generales',
    'I accept the': 'Acepto las',
    'General Conditions': 'Condiciones Generales',
    //CLAIM-STATUS-PIPE
    "Processing the claim.": "Tramitando la reclamación.",
    "Claiming to the airline.": "Reclamando a la aerolínea.",
    "Administrative procedures, the waiting time lasts up to 4 months.": "Trámites administrativos, el tiempo de espera dura hasta un máximo de 4 meses.",
    "Seconds administrative procedures, the waiting time lasts up to a maximum of one month.": "Segundos trámites administrativos, el tiempo de espera dura hasta un máximo de un mes.",
    "Term of payment by the airline, the waiting time lasts up to a maximum of one month.": "Plazo de pago por parte de la aerolínea, el tiempo de espera dura hasta un máximo de un mes.",
    "Legal proceedings.": "Trámites judiciales.",
    "Judicial order of payment in process.": "Mandato judicial de pago en proceso.",
    "Compensation paid.": "Compensación pagada.",
    "Claim without right to compensation.": "Reclamación sin derecho a compensación.",
};
