export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  //NON-LOGGED-HOME COMPONENT
    'We only charge': 'We only charge',
    'if you win': 'if you win',
    "It will take you only a minute to claim your flight, it's that easy!": "It will take you only a minute to claim your flight, it's that easy!",
    'Check compensation': 'Check compensation',
    'What can I claim?': 'What can I claim?',
    'Delay': 'Delay',
    'You can get up to € 600 for any delay over 3 hours.': 'You can get up to € 600 for any delay over 3 hours.',
    'Cancellation': 'Cancellation',
    'If your flight has been cancelled or you have been assigned a different one, airlines owe you a compensation.': 'If your flight has been cancelled or you have been assigned a different one, airlines owe you a compensation.',
    'Overbooking': 'Overbooking',
    'You are entitled to compensation in case of denied boarding.': 'You are entitled to compensation in case of denied boarding.',
    'How does Fly&amp;Claim work?': 'How does Fly&amp;Claim work?',
    'Fill our form': 'Fill our form',
    'Enter your flight information and see if you are entitled to compensation, it will take you less than a minute!': 'Enter your flight information and see if you are entitled to compensation, it will take you less than a minute!',
    'Our experts process your case': 'Our experts process your case',
    'We have a team of professionals whose success rate is 99%. Forget about the paperwork, at Fly&Claim we take care of everything!': 'We have a team of professionals whose success rate is 99%. Forget about the paperwork, at Fly&Claim we take care of everything!',
    "You get your money, it's that easy!": "You get your money, it's that easy!",
    'Once your claim is resolved, you will receive your money immediately. You can get from 250 to 600 euros per passenger.': 'Once your claim is resolved, you will receive your money immediately. You can get from 250 to 600 euros per passenger.',
    'We only charge if you win': 'We only charge if you win',
    'Up to 600€ per person': 'Up to 600€ per person',
    'Forget about the paperwork': 'Forget about the paperwork',
    'We inform you step by step of the process': 'We inform you step by step of the process',
    //APP COMPONENT
    'Terms and Conditions': 'Terms and Conditions',
    'Privacy policy': 'Privacy policy',
    'Cookies policy': 'Cookies policy',
    'Bienvenido a FlyAndClaim. Al continuar navegando consideramos que aceptas nuestra': 'Welcome to FlyAndClaim. By continuing browsing we consider that you accept our',
    'cookies policy.': 'cookies policy.',
    //SHARE-PROMO-COMPONENT
    'How does it work?': 'How does it work?',
    'Log in': 'Log in',
    'or sign up': 'or sign up',
    'You will get a promotional code that you can share with anyone who has had an incident on your flight.': 'You will get a promotional code that you can share with anyone who has had an incident on your flight.',
    'Win 10€ each time': 'Win 10€ each time',
    'they use your code': 'they use your code',
    'Share your promotional code. Friends, family, travel partners, anyone can be entitled to compensation and not know it.': 'Share your promotional code. Friends, family, travel partners, anyone can be entitled to compensation and not know it.',
    'Everybody': 'Everybody',
    'wins': 'wins',
    'If a passenger uses your code they will receive 10€ more in their compensation. Convince them and make them win more!': 'If a passenger uses your code they will receive 10€ more in their compensation. Convince them and make them win more!',
    'Control your': 'Control your',
    'activity': 'activity',
    'You can see the status of your promotions in the section': 'You can see the status of your promotions in the section',
    'Your promotional code': 'Your promotional code',
    //NAV-HEADER-COMPONENT
    'End claim': 'End claim',
    'Contact': 'Contact',
    'Share and earn money': 'Share and earn money',
    'Log out': 'Log out',
    'My claims': 'My claims',
    'Your promotional code:': 'Your promotional code:',
    'Home': 'Home',
    //LOGIN-COMPONENT
    'Login with Facebook': 'Login with Facebook',
    'Login with Google': 'Login with Google',
    'E-mail': 'E-mail',
    'Required field': 'Required field',
    'Invalid email format': 'Invalid email format',
    'Incorrect email address': 'Incorrect email address',
    'Password': 'Password',
    'Invalid password': 'Invalid password',
    'Have you forgotten your password?': 'Have you forgotten your password?',
    'Don´t you have an account?': 'Don´t you have an account?',
    'Sign up': 'Sign up',
    'or': 'or',
    //REGISTER-COMPONENT
    'Sign up with Facebook': 'Sign up with Facebook',
    'Sign up with Google': 'Sign up with Google',
    'Name': 'Name',
    'This email address already exists, try another': 'This email address already exists, try another',
    'Already have an account in Fly&Claim?': 'Already have an account in Fly&Claim?',
    //FORGOT-PASSWORD-COMPONENT
    'Restore password': 'Restore password',
    'Enter the email address associated with your account and we will send you a link to reset your password.': 'Enter the email address associated with your account and we will send you a link to reset your password.',
    'Return to Login': 'Return to Login',
    'Send link': 'Send link',
    //LOGGED-HOME-COMPONENT
    'Hello': 'Hello',
    'Thank you for finalizing your claim. Your promotional code is the': 'Thank you for finalizing your claim. Your promotional code is the',
    ', click': ', click',
    'here': 'here',
    'if you want to see your activity.': 'if you want to see your activity.',
    'Your promotional code is the': 'Your promotional code is the',
    'You have': 'You have',
    'pending claim to complete': 'pending claim to complete',
    'pending claims to complete': 'pending claims to complete',
    'from': 'from',
    ', to': ', to',
    ', claim created on': ', claim created on',
    'Complete': 'Complete',
    'You have completed': 'You have completed',
    'claim': 'claim',
    'claims': 'claims',
    'Incidence': 'Incidence',
    'Status': 'Status',
    //MY-PROMO-COMPONENT
    'Your promotional': 'Your promotional',
    'code': 'code',
    'If you want to know how you can earn money by sharing, click': 'If you want to know how you can earn money by sharing, click',
    'Your activity': 'Your activity',
    'Code used': 'Code used',
    'euros': 'euros',
    'aware of payment': 'aware of payment',
    'earned': 'earned',
    'invalid': 'invalid',
    'promotions': 'promotions',
    'time': 'time',
    'times': 'times',
    //CONTACT-COMPONENT
    'Contact us': 'Contact us',
    'with us': ' ',
    'We are happy to answer any questions you may have, just send us a message to our email or give us a call any day of the week from 9:30 a.m. to 9:30 p.m.': 'We are happy to answer any questions you may have, just send us a message to our email or give us a call any day of the week from 9:30 a.m. to 9:30 p.m.',
    'Telephone': 'Telephone',
    //CLAIM-COMPONENT
    'Check your': 'Check your',
    'compensation': 'compensation',
    'Airlines owe you': 'Airlines owe you',
    'per passenger': 'per passenger',
    'Log in or sign up': 'Log in or sign up',
    'to earn your': 'to earn your',
    "Congratulations, you've got": "Congratulations, you've got",
    'more thanks to the promotional code!': 'more thanks to the promotional code!',
    'Finish your claim and our experts will process your compensation': 'Finish your claim and our experts will process your compensation',
    //SECOND-PART-CLAIM-COMPONENT
    'Airport where the incident occurred': 'Airport where the incident occurred',
    'Promotional code (opt)': 'Promotional code (opt)',
    'Flight year': 'Flight year',
    'Required': 'Required',
    'Address': 'Address',
    'ZIP': 'ZIP',
    'City': 'City',
    'Country': 'Country',
    'Did you complain to the airline?': 'Did you complain to the airline?',
    'YES': 'YES',
    'NO': 'NO',
    'Do you have the flight reservation or ticket?': 'Do you have the flight reservation or ticket?',
    'Do you have the boarding pass?': 'Do you have the boarding pass?',
    'Tell us what happened (opt)': 'Tell us what happened (opt)',
    //RED-DIV-COMPONENT
    'Remember that if you do not have the flight reservation or ticket, or the boarding pass, we will not be able to process your claim.': 'Remember that if you do not have the flight reservation or ticket, or the boarding pass, we will not be able to process your claim.',
    'You must attach at least one of these three documents:': 'You must attach at least one of these three documents:',
    'Flight reservation.': 'Flight reservation.',
    'Flight ticket.': 'Flight ticket.',
    'Boarding pass.': 'Boarding pass.',
    'You can find your flight reservation in the confirmation email that the airline sent you when you bought the tickets.': 'You can find your flight reservation in the confirmation email that the airline sent you when you bought the tickets.',
    'Try searching the name of the airline in your email to find the reservation.': 'Try searching the name of the airline in your email to find the reservation.',
    'If you need help to find any of the above documents, send us an email to info@flyandclaim.com': 'If you need help to find any of the above documents, send us an email to info@flyandclaim.com',
    //ID-FRONT-COMPONENT
    'Attach front image of ID / Passport': 'Attach front image of ID / Passport',
    'Front image of ID / Passport': 'Front image of ID / Passport',
    //ID-BACK-COMPONENT
    'Attach back image of ID': 'Attach back image of ID',
    'Back image of ID': 'Back image of ID',
    //FLIGHT-TICKET-OR-RESERVATION-COMPONENT
    'Attach reservation or flight ticket': 'Attach reservation or flight ticket',
    //COMPANY-CLAIM-COMPONENT
    'Attach claim to the airline': 'Attach claim to the airline',
    //BOARDING-PASS-COMPONENT
    'Attach boarding pass': 'Attach boarding pass',
    //NO-C0MPENSATION-COMPONENT
    'We are sorry,': 'We are sorry,',
    'this flight does not give you the right': 'this flight does not give you the right',
    'to receive compensation': 'to receive compensation',
    'If you still believe that you are entitled to compensation or have doubts, contact us:': 'If you still believe that you are entitled to compensation or have doubts, contact us:',
    //FIRST-PART-CLAIM-COMPONENT
    'From': 'From',
    'To': 'To',
    'Direct flight': 'Direct flight',
    'Flights with a stop': 'Flights with a stop',
    'Airline': 'Airline',
    'Delay less than 3 hours': 'Delay less than 3 hours',
    'Delay greater than 3 hours': 'Delay greater than 3 hours',
    'Add another stop': 'Add another stop',
    'You must accept the General Conditions': 'You must accept the General Conditions',
    'I accept the': 'I accept the',
    'General Conditions': 'General Conditions',
    //cuidado con esto
    'Retraso inferior a 3 horas': 'Delay less than 3 hours',
    'Retraso superior a 3 horas': 'Delay greater than 3 hours',
    'Cancelación': 'Cancellation',
    //CLAIM-STATUS-PIPE
    "Processing the claim.": "Processing the claim.",
    "Claiming to the airline.": "Claiming to the airline.",
    "Administrative procedures, the waiting time lasts up to 4 months.": "Administrative procedures, the waiting time lasts up to 4 months.",
    "Seconds administrative procedures, the waiting time lasts up to a maximum of one month.": "Seconds administrative procedures, the waiting time lasts up to a maximum of one month.",
    "Term of payment by the airline, the waiting time lasts up to a maximum of one month.": "Term of payment by the airline, the waiting time lasts up to a maximum of one month.",
    "Legal proceedings.": "Legal proceedings.",
    "Judicial order of payment in process.": "Judicial order of payment in process.",
    "Compensation paid.": "Compensation paid.",
    "Claim without right to compensation.": "Claim without right to compensation.",
  };
